name: Java 17 · Maven · TestNG · Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Download Chrome browser
        uses: browser-actions/setup-chrome@v1

      - name: Download ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: 'latest'
          
      - name: Run tests
        run: mvn clean test
